# Generated by Django 4.1.7 on 2023-04-25 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 10, 57, 29, 317295, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
